name: Docker Image CI

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:   

env:
  IMAGE_NAME: asasfans-api

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Login to image-repository , build and push
        uses: azure/docker-login@v1
        with:
         login-server: ${{ secrets.ACR_ENDPOINT }}
         username: ${{ secrets.ACR_USERNAME }}
         password: ${{ secrets.ACR_PASSWORD }}
         
      - run: |
         docker build -f ./builder/asasapi/Dockerfile . -t ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
         docker push ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
         docker tag ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:latest
         docker push ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:latest
