name: Docker Image CI

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:   

env:
  IMAGE_NAME: asasfans-api
  IMAGE_NAME02: asasfans-spider

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Login to image-repository , build and push
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - run: |
         docker build -f ./builder/asasapi/Dockerfile . -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
         docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

         docker build -f ./builder/asasspider/Dockerfile . -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME02 }}:${{ steps.tag.outputs.tag }}
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME02 }}:${{ steps.tag.outputs.tag }}
         docker tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME02 }}:${{ steps.tag.outputs.tag }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME02 }}:latest
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME02 }}:latest